services:
  access:
    image: gcr.io/flow-container-registry/access:${FLOW_GO_NODE_VERSION}
    command: >-
      --nodeid ${FLOW_GO_NODE_ID}
      --bootstrapdir /bootstrap
      --datadir /data/protocol
      --rpc-addr 0.0.0.0:9000
      --http-addr 0.0.0.0:8000
      --collection-ingress-port 9000
      --bind 0.0.0.0:3569
      --loglevel ERROR
    volumes:
      - ./bootstrap:/bootstrap:ro
      - ./data:/data:rw
    ports:
      - 9000
      - 8000
      - 3569
